"""changed images table to have a is_annotated columns

Revision ID: 357f056f9aa3
Revises: 935a220cc69d
Create Date: 2025-12-16 21:23:11.158942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357f056f9aa3'
down_revision: Union[str, Sequence[str], None] = '935a220cc69d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_annotated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_annotated')
    # ### end Alembic commands ###
