"""added project table and updated relationships

Revision ID: b324b1638599
Revises: e10daa73c33c
Create Date: 2025-12-21 15:51:08.178325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b324b1638599'
down_revision: Union[str, Sequence[str], None] = 'e10daa73c33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.drop_constraint(op.f('annotations_user_id_fkey'), 'annotations', type_='foreignkey')
    op.drop_column('annotations', 'user_id')
    op.add_column('images', sa.Column('project_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('images_user_id_fkey'), 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'])
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key(op.f('images_user_id_fkey'), 'images', 'users', ['user_id'], ['id'])
    op.drop_column('images', 'project_id')
    op.add_column('annotations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('annotations_user_id_fkey'), 'annotations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
