"""changed images table to have a is_annotated columns

Revision ID: e10daa73c33c
Revises: 357f056f9aa3
Create Date: 2025-12-16 21:27:03.731162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10daa73c33c'
down_revision: Union[str, Sequence[str], None] = '357f056f9aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'is_annotated',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'is_annotated',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
